# Generated by Django 4.0.3 on 2023-03-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='samples',
            field=models.URLField(blank=True, help_text='Enter a link to samples of previous work', null=True),
        ),
    ]
