# Generated by Django 4.0.3 on 2023-03-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_skill_name_alter_skill_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set(),
        ),
    ]
