# Generated by Django 4.0.3 on 2023-03-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_skill_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='service.category'),
        ),
    ]
