# Generated by Django 4.0.3 on 2023-03-26 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0009_alter_service_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('delivery_time', models.IntegerField(help_text='Enter delivery time in days')),
                ('revisions', models.IntegerField(default=0, help_text='Enter the number of revisions included in the service')),
                ('is_taken', models.BooleanField(default=False)),
                ('samples', models.URLField(blank=True, help_text='Enter a link to samples of previous work', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='categories_forSale', to='service.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellservices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
