# Generated by Django 4.0.3 on 2023-03-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_sellservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellservice',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='Sell_categories', to='service.category'),
        ),
    ]
