# Generated by Django 4.0.3 on 2023-03-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellservice',
            old_name='user',
            new_name='seller',
        ),
    ]
