# Generated by Django 4.0.3 on 2023-03-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_alter_rating_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='average_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='rating',
            name='ratings_num',
            field=models.IntegerField(default=0),
        ),
    ]
