# Generated by Django 4.0.3 on 2023-03-29 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_rating_average_value_rating_ratings_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='average_value',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='ratings_num',
        ),
    ]
