# Generated by Django 4.0.3 on 2023-04-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='other_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
