# Generated by Django 4.0.3 on 2023-04-01 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_report_other_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='count',
        ),
    ]
