# Generated by Django 4.0.3 on 2022-09-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='toto',
        ),
    ]
