# Generated by Django 4.0.3 on 2022-09-02 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_is_active_user_is_activee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_activee',
            new_name='is_Active',
        ),
    ]
