# Generated by Django 4.0.3 on 2022-09-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_Active',
            field=models.BooleanField(default=True),
        ),
    ]
