# Generated by Django 4.0.3 on 2022-09-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_rename_is_active_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='Active',
        ),
    ]
