# Generated by Django 4.0.3 on 2022-09-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_rename_is_active_user_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Active',
            new_name='is_active',
        ),
    ]
