# Generated by Django 4.0.3 on 2022-09-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_rename_active_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
