# Generated by Django 4.0.3 on 2023-03-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.TextField(blank=True, default=''),
        ),
    ]
