# Generated by Django 4.0.3 on 2023-04-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_user_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Active',
        ),
    ]
